# Generated by Django 4.2.14 on 2024-07-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='blog',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(),
        ),
    ]
